### ISSUE TITLE
Incompatible change in pageLabel

### ISSUE THREAD

**Issue by sciurius** [ssimms/pdfapi2#40]
Before the last changes, `pageLabel` accepted style arguments `roman`, `arabic`, etc.
In 2.042, it merely takes the first letter (provided it is `a`, `d` or `r`). 
In short, `arabic` now comes out as __a__ (lowercase letters) instead of __D__ (Decimal arabic numerals).

See https://github.com/ssimms/pdfapi2/pull/39 for a possible fix.

**Comment by ssimms** [comment]
That's an interesting backward compatibility bug.  `arabic` wasn't a valid/documented value for `-style` (documented options were Roman, roman, Alpha, alpha, and decimal), but it happened to work because the if statement defaulted to decimal, as you noted in your suggested fix.

I've implemented a similar fix, with the addition of a warning if pageLabel is passed an invalid value.
